#!/bin/bash

# Check if the script is run as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit
fi

# User whose password needs to be changed
USER_TO_CHANGE="your_username_here"

# Your email address
EMAIL="your_email@example.com"

# Generate a random strong password of 32 characters
PASSWORD=$(openssl rand -base64 32 | tr -d /=+ | cut -c -32)

# Change the password
echo "$USER_TO_CHANGE:$PASSWORD" | chpasswd

# Expire the password so the user has to reset it upon next login
passwd -e $USER_TO_CHANGE

# Send an email notification
echo "Password for $USER_TO_CHANGE has been changed and expired. The user will need to reset their password upon next login." | mail -s "Password Change Notification" $EMAIL

echo "Password change and expiration process completed."
