#!/bin/bash
# This is your test.sh script

if [ -z "$1" ]
then
    echo "No argument supplied, going to next block..."

    # Read from a file
    while IFS= read -r line
    do
        input_variable_from_file="$line"
    done < "file.txt"

    echo "The input variable from the file is: $input_variable_from_file"

    # Continue with the rest of your script
else
    input_variable=$1 
    echo "The input variable is: $input_variable"
    # You can continue your script here
fi


#comment